language: ruby
rvm:
  - "2.2.0"
env: 
  - RAILS_ENV=test
before_script:
  - psql -c 'create database my_app_test' -U postgres
  - "cp ./.travis.database.yml ./config/database.yml"
script: 
  bundle exec rake db:schema:load
  bundle exec rake db:test:prepare
  bundle exec rspec
